import { LOTTIE_ASSETS } from "@/lib/lottie-frames";
import type { FrameTheme, ShopItem } from "@/lib/shop-items";

/** Color / detail variants derived from base frame themes. */
export const SHOP_VARIANT_ITEMS: ShopItem[] = [
  // common static
  {
    slug: "frame-ember-crimson",
    name: "赤烬脉冲框",
    description: "余烬系换色 · 深红脉冲光环，边框略加粗光晕。",
    type: "avatar_frame",
    price: 140,
    rarity: "common",
  },
  {
    slug: "frame-ember-ash",
    name: "灰烬余烬框",
    description: "余烬系换色 · 灰橙低调款，适合暗色主题。",
    type: "avatar_frame",
    price: 140,
    rarity: "common",
  },
  {
    slug: "frame-ion-frost",
    name: "霜离子框",
    description: "离子系换色 · 冰蓝冷光，清爽偏白。",
    type: "avatar_frame",
    price: 140,
    rarity: "common",
  },
  {
    slug: "frame-ion-jade",
    name: "翡翠离子框",
    description: "离子系换色 · 青绿离子流，生机感边框。",
    type: "avatar_frame",
    price: 150,
    rarity: "common",
  },
  // rare animated
  {
    slug: "frame-nebula-rose",
    name: "玫瑰星云框",
    description: "星云系换色 · 粉紫星环宝石，旋转节奏与星云框相同。",
    type: "avatar_frame",
    price: 580,
    rarity: "rare",
  },
  {
    slug: "frame-nebula-teal",
    name: "青霭星云框",
    description: "星云系换色 · 青绿星环，宝石点缀更密集。",
    type: "avatar_frame",
    price: 580,
    rarity: "rare",
  },
  {
    slug: "frame-entropy-blood",
    name: "赤熵流环",
    description: "熵流系换色 · 暗红双轨逆流，压迫感更强。",
    type: "avatar_frame",
    price: 580,
    rarity: "rare",
  },
  {
    slug: "frame-entropy-frost",
    name: "冰熵流环",
    description: "熵流系换色 · 冰蓝逆流轨道，冷冽科幻感。",
    type: "avatar_frame",
    price: 580,
    rarity: "rare",
  },
  // epic prism
  {
    slug: "frame-solar-ember",
    name: "赤日冕环",
    description: "日冕系换色 · 赤金棱镜轨道，暖色折光。",
    type: "avatar_frame",
    price: 1150,
    rarity: "epic",
  },
  {
    slug: "frame-solar-aurora",
    name: "极光日冕环",
    description: "日冕系换色 · 绿金极光棱镜，轨道更亮。",
    type: "avatar_frame",
    price: 1150,
    rarity: "epic",
  },
  {
    slug: "frame-quantum-rose",
    name: "玫瑰量子框",
    description: "量子系换色 · 玫红×青棱镜，高速轨道换色版。",
    type: "avatar_frame",
    price: 1150,
    rarity: "epic",
  },
  {
    slug: "frame-quantum-violet",
    name: "紫晶量子框",
    description: "量子系换色 · 深紫×电蓝，折光层次更丰富。",
    type: "avatar_frame",
    price: 1200,
    rarity: "epic",
  },
  // legendary lottie
  {
    slug: "frame-void-eclipse",
    name: "蚀空裂隙框",
    description: "传说换色 · 深蚀羽翼动效，外环脉冲增强。",
    type: "avatar_frame",
    price: 10000,
    rarity: "legendary",
  },
  {
    slug: "frame-void-crimson",
    name: "赤渊裂隙框",
    description: "传说换色 · 赤红羽翼 Lottie，裂隙感更强。",
    type: "avatar_frame",
    price: 10000,
    rarity: "legendary",
  },
  {
    slug: "frame-ascension-dawn",
    name: "晨曦升格框",
    description: "传说换色 · 暖金羽翼，晨光渐变增强。",
    type: "avatar_frame",
    price: 10000,
    rarity: "legendary",
  },
  {
    slug: "frame-ascension-nova",
    name: "星爆升格框",
    description: "传说换色 · 冷蓝星爆羽翼，高亮脉冲外环。",
    type: "avatar_frame",
    price: 10000,
    rarity: "legendary",
  },
  // title badges — common
  {
    slug: "badge-scribe",
    name: "抄写员铭牌",
    description: "读者系换色 · 石墨灰蓝，低调书写者。",
    type: "title_badge",
    price: 55,
    rarity: "common",
    badgeLabel: "抄写员",
  },
  {
    slug: "badge-voyager",
    name: "航行者徽章",
    description: "观星系换色 · 深空青，航程旅人。",
    type: "title_badge",
    price: 95,
    rarity: "common",
    badgeLabel: "航行者",
  },
  {
    slug: "badge-drifter",
    name: "漂流者徽章",
    description: "漫游系换色 · 薄荷青，星际漂流气质。",
    type: "title_badge",
    price: 130,
    rarity: "common",
    badgeLabel: "漂流者",
  },
  {
    slug: "badge-autumn",
    name: "秋叶铭牌",
    description: "余烬色称号 · 暖橙落叶光晕。",
    type: "title_badge",
    price: 75,
    rarity: "common",
    badgeLabel: "秋叶",
  },
  // rare
  {
    slug: "badge-curator",
    name: "策展人徽章",
    description: "档案系换色 · 钢蓝光泽，典藏管理者。",
    type: "title_badge",
    price: 200,
    rarity: "rare",
    badgeLabel: "策展人",
  },
  {
    slug: "badge-rift",
    name: "裂隙客徽章",
    description: "熵行系换色 · 暗红紫脉动，裂隙行者。",
    type: "title_badge",
    price: 280,
    rarity: "rare",
    badgeLabel: "裂隙客",
  },
  {
    slug: "badge-lens",
    name: "透镜师徽章",
    description: "观测系换色 · 银蓝透镜边框流光。",
    type: "title_badge",
    price: 320,
    rarity: "rare",
    badgeLabel: "透镜师",
  },
  {
    slug: "badge-nebula",
    name: "星云客徽章",
    description: "星云色称号 · 粉紫星云渐变。",
    type: "title_badge",
    price: 230,
    rarity: "rare",
    badgeLabel: "星云客",
  },
  // epic
  {
    slug: "badge-harbinger",
    name: "先驱徽章",
    description: "神谕系换色 · 深紫辉光 shimmer。",
    type: "title_badge",
    price: 420,
    rarity: "epic",
    badgeLabel: "先驱",
  },
  {
    slug: "badge-chromatic",
    name: "折光者徽章",
    description: "棱镜系换色 · 高饱和七彩流动。",
    type: "title_badge",
    price: 520,
    rarity: "epic",
    badgeLabel: "折光者",
  },
  {
    slug: "badge-dawn",
    name: "晨曦徽章",
    description: "日冕色称号 · 金橙晨曦渐变。",
    type: "title_badge",
    price: 440,
    rarity: "epic",
    badgeLabel: "晨曦",
  },
  // legendary (repriced + new)
  {
    slug: "badge-eclipse",
    name: "蚀刻者徽章",
    description: "传说铭牌 · 深空蚀刻脉冲，虚空系强化光效。",
    type: "title_badge",
    price: 3200,
    rarity: "legendary",
    badgeLabel: "蚀刻者",
  },
  {
    slug: "badge-sovereign",
    name: "主权者徽章",
    description: "传说铭牌 · 金白主权流光，仅次于先知档。",
    type: "title_badge",
    price: 3600,
    rarity: "legendary",
    badgeLabel: "主权者",
  },
];

export const SHOP_VARIANT_FRAME_THEMES: Record<string, FrameTheme> = {
  "frame-ember-crimson": {
    id: "ember-crimson",
    primary: "#ef4444",
    secondary: "#b91c1c",
    accent: "#fca5a5",
    glow: "#f87171",
    rarity: "common",
    frameStyle: "static",
  },
  "frame-ember-ash": {
    id: "ember-ash",
    primary: "#d97706",
    secondary: "#78716c",
    accent: "#fcd34d",
    glow: "#a8a29e",
    rarity: "common",
    frameStyle: "static",
  },
  "frame-ion-frost": {
    id: "ion-frost",
    primary: "#bae6fd",
    secondary: "#38bdf8",
    accent: "#e0f2fe",
    glow: "#7dd3fc",
    rarity: "common",
    frameStyle: "static",
  },
  "frame-ion-jade": {
    id: "ion-jade",
    primary: "#34d399",
    secondary: "#059669",
    accent: "#a7f3d0",
    glow: "#10b981",
    rarity: "common",
    frameStyle: "static",
  },
  "frame-nebula-rose": {
    id: "nebula-rose",
    primary: "#f472b6",
    secondary: "#db2777",
    accent: "#fce7f3",
    glow: "#f9a8d4",
    rarity: "rare",
    frameStyle: "gems",
  },
  "frame-nebula-teal": {
    id: "nebula-teal",
    primary: "#2dd4bf",
    secondary: "#0d9488",
    accent: "#ccfbf1",
    glow: "#5eead4",
    rarity: "rare",
    frameStyle: "gems",
  },
  "frame-entropy-blood": {
    id: "entropy-blood",
    primary: "#dc2626",
    secondary: "#7f1d1d",
    accent: "#fecaca",
    glow: "#ef4444",
    rarity: "rare",
    frameStyle: "entropy",
  },
  "frame-entropy-frost": {
    id: "entropy-frost",
    primary: "#60a5fa",
    secondary: "#1e3a8a",
    accent: "#dbeafe",
    glow: "#3b82f6",
    rarity: "rare",
    frameStyle: "entropy",
  },
  "frame-solar-ember": {
    id: "solar-ember",
    primary: "#f97316",
    secondary: "#c2410c",
    accent: "#fed7aa",
    glow: "#fb923c",
    rarity: "epic",
    frameStyle: "prism",
  },
  "frame-solar-aurora": {
    id: "solar-aurora",
    primary: "#84cc16",
    secondary: "#ca8a04",
    accent: "#ecfccb",
    glow: "#a3e635",
    rarity: "epic",
    frameStyle: "prism",
  },
  "frame-quantum-rose": {
    id: "quantum-rose",
    primary: "#fb7185",
    secondary: "#e11d48",
    accent: "#22d3ee",
    glow: "#f472b6",
    rarity: "epic",
    frameStyle: "prism",
  },
  "frame-quantum-violet": {
    id: "quantum-violet",
    primary: "#8b5cf6",
    secondary: "#4c1d95",
    accent: "#22d3ee",
    glow: "#a78bfa",
    rarity: "epic",
    frameStyle: "prism",
  },
  "frame-void-eclipse": {
    id: "void-eclipse",
    primary: "#1e1b4b",
    secondary: "#0f0a1e",
    accent: "#6366f1",
    glow: "#312e81",
    rarity: "legendary",
    lottieSrc: LOTTIE_ASSETS.avatarFrame,
    lottieFilter: "hue-rotate(220deg) saturate(1.35) brightness(0.72) contrast(1.1)",
  },
  "frame-void-crimson": {
    id: "void-crimson",
    primary: "#be123c",
    secondary: "#4c0519",
    accent: "#fda4af",
    glow: "#e11d48",
    rarity: "legendary",
    lottieSrc: LOTTIE_ASSETS.avatarFrame,
    lottieFilter: "hue-rotate(320deg) saturate(1.4) brightness(0.85)",
  },
  "frame-ascension-dawn": {
    id: "ascension-dawn",
    primary: "#fbbf24",
    secondary: "#f97316",
    accent: "#fef3c7",
    glow: "#fcd34d",
    rarity: "legendary",
    lottieSrc: LOTTIE_ASSETS.avatarFrame,
    lottieFilter: "hue-rotate(25deg) saturate(1.25) brightness(1.05)",
  },
  "frame-ascension-nova": {
    id: "ascension-nova",
    primary: "#38bdf8",
    secondary: "#6366f1",
    accent: "#e0f2fe",
    glow: "#22d3ee",
    rarity: "legendary",
    lottieSrc: LOTTIE_ASSETS.avatarFrame,
    lottieFilter: "hue-rotate(180deg) saturate(1.3) brightness(1.08)",
  },
};

export const SHOP_VARIANT_BADGE_CLASSES: Record<string, string> = {
  "badge-scribe": "title-badge-scribe",
  "badge-voyager": "title-badge-voyager",
  "badge-drifter": "title-badge-drifter",
  "badge-autumn": "title-badge-autumn",
  "badge-curator": "title-badge-curator",
  "badge-rift": "title-badge-rift",
  "badge-lens": "title-badge-lens",
  "badge-nebula": "title-badge-nebula",
  "badge-harbinger": "title-badge-harbinger",
  "badge-chromatic": "title-badge-chromatic",
  "badge-dawn": "title-badge-dawn",
  "badge-eclipse": "title-badge-eclipse",
  "badge-sovereign": "title-badge-sovereign",
};
